# Generated by Django 6.0.6 on 2026-06-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
