# Generated by Django 6.0.6 on 2026-07-01 22:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_phone_resident_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='potholereport',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
