# Generated by Django 6.0.6 on 2026-07-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_potholereport_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potholereport',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
