# Generated by Django 6.0.6 on 2026-07-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_potholereport_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potholereport',
            name='severity',
            field=models.CharField(choices=[('n/a', 'Not Assessed'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='n/a', max_length=20),
        ),
    ]
