# Generated by Django 6.0.6 on 2026-07-24 04:45

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_potholereport_severity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statushistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Status and Activity History', 'verbose_name_plural': 'Status and Activity Histories'},
        ),
        migrations.AddField(
            model_name='statushistory',
            name='activity_type',
            field=models.CharField(choices=[('status_updated', 'Status Updated'), ('details_updated', 'Report Details Updated'), ('location_updated', 'Location Updated'), ('severity_updated', 'Severity Updated'), ('notes_updated', 'Notes Updated'), ('multiple_updates', 'Multiple Updates')], default='status_updated', max_length=30),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='change_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='potholereport',
            name='public_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='potholereport',
            name='staff_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='potholereport',
            name='ticket_number',
            field=models.CharField(default=reports.models.generate_ticket, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.staff'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('closed', 'Closed')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('closed', 'Closed')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='public_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='staff_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
